/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-18 06:53:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;

public final class busSeat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("margin:0px;\r\n");
      out.write("font-family:candara;\r\n");
      out.write("}\r\n");
      out.write(".header{\r\n");
      out.write("height:150px;\r\n");
      out.write("width:100%;\r\n");
      out.write("background-color:#25488e;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:space-around;\r\n");
      out.write("align-items:center;\r\n");
      out.write("}\r\n");
      out.write(".plane{\r\n");
      out.write("height:100px;\r\n");
      out.write("width:250px;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("align-items:center;\r\n");
      out.write("}\r\n");
      out.write(".title{\r\n");
      out.write("height:120px;\r\n");
      out.write("width:700px;\r\n");
      out.write("}\r\n");
      out.write(".home{\r\n");
      out.write("height:120px;\r\n");
      out.write("width:120px;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("align-items:center;\r\n");
      out.write("flex-direction:column;\r\n");
      out.write("}\r\n");
      out.write(".home:hover{\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(".parent{\r\n");
      out.write("height:1400px;\r\n");
      out.write("width:100%;\r\n");
      out.write("background-color:#c2d1ef;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("align-items:center;\r\n");
      out.write("}\r\n");
      out.write(".child{\r\n");
      out.write("height:1100px;\r\n");
      out.write("width:700px;\r\n");
      out.write("background-color:white;\r\n");
      out.write("display:flex;\r\n");
      out.write("align-items:center;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("flex-direction:column;\r\n");
      out.write("}\r\n");
      out.write(".b1{\r\n");
      out.write("height:35px;\r\n");
      out.write("width:300px;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("border-radius:4px;\r\n");
      out.write("}\r\n");
      out.write(".b1:hover{\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("background-color:#25488e;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write(".test{\r\n");
      out.write("height:30px;\r\n");
      out.write("width:30px;\r\n");
      out.write(" color: green;\r\n");
      out.write("  background-color: green;\r\n");
      out.write("}\r\n");
      out.write(".seat{\r\n");
      out.write("height:550px;\r\n");
      out.write("width:500px;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content: center;\r\n");
      out.write("align-items: center;\r\n");
      out.write("border:solid black 1px;\r\n");
      out.write("flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write(".t1{\r\n");
      out.write("display:none;\r\n");
      out.write("}\r\n");
      out.write(".t2{\r\n");
      out.write("display:none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src='javascript/jquery-3.4.1.js'>\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#r1\").click(function(){\r\n");
      out.write("\t$(\".t2\").hide();\r\n");
      out.write("\t$(\".t1\").toggle(\"slow\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#r2\").click(function(){\r\n");
      out.write("\t$(\".t1\").hide();\r\n");
      out.write("\t$(\".t2\").toggle(\"slow\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#r3\").click(function(){\r\n");
      out.write("\t$(\".t1\").hide();\r\n");
      out.write("\t$(\".t2\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("function display(id)\r\n");
      out.write("{\r\n");
      out.write("\tvar total = document.getElementById('ammt').value;\r\n");
      out.write("\tif(document.getElementById(id).checked == true)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar result = new XMLHttpRequest();\r\n");
      out.write("\t\tresult.onreadystatechange = function(){\r\n");
      out.write("\t\t\tif(this.readyState == 4 && this.status == 200)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar x = document.getElementById(\"ammt\");\r\n");
      out.write("\t\t\t\tx.value = this.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tresult.open(\"GET\",\"CheckSeat.jsp?total=\"+total,true);\r\n");
      out.write("\t\tresult.send();\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar result = new XMLHttpRequest();\r\n");
      out.write("\t\tresult.onreadystatechange = function(){\r\n");
      out.write("\t\t\tif(this.readyState == 4 && this.status == 200)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar x = document.getElementById(\"ammt\");\r\n");
      out.write("\t\t\t\tx.value = this.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tresult.open(\"GET\",\"CheckSeat1.jsp?total=\"+total,true);\r\n");
      out.write("\t\tresult.send();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"css/all.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"BusSeat\" method=\"POST\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String from=request.getParameter("from");
String to=request.getParameter("to");
String bdate=request.getParameter("bdate");

Cookie cookie7=new Cookie("bfrom",from+"");
Cookie cookie8=new Cookie("bto",to+"");
Cookie cookie9=new Cookie("bdate",bdate+"");
response.addCookie(cookie7);
response.addCookie(cookie8);
response.addCookie(cookie9);

      out.write('\r');
      out.write('\n');

	if(from.equals(to))
	{
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\talert(\"No Bus Available\");\r\n");
      out.write("\t\t\t\t\tdocument.location.href=\"bus.jsp\";\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t");
 }
	String bname="";
	String busdate="";
	String sa1="",sa2="",sa3="",sa4="";
	String sb1="",sb2="",sb3="",sb4="";
	String sc1="",sc2="",sc3="",sc4="";
	String sd1="",sd2="",sd3="",sd4="";
	String se1="",se2="",se3="",se4="";
	Connection con=null;
	String url="jdbc:ucanaccess://E://Database//bus.accdb";
	try{
		Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
		con=DriverManager.getConnection(url);
		Statement stmt = con.createStatement();
		ResultSet rs=stmt.executeQuery("select * from bus where source='"+from+"' and destination='"+to+"'");
		while(rs.next())
		{
			bname=rs.getString("busname");
			busdate=rs.getString("bdate");
		}
		if(busdate.equals(bdate))
		{
			PreparedStatement ps1=con.prepareStatement("SELECT status from "+bname+" where seat='A1'");
			ResultSet rs1=ps1.executeQuery();
			while(rs1.next())
			{
				sa1=rs1.getString("status");
			}
			
			PreparedStatement ps2=con.prepareStatement("SELECT status from "+bname+" where seat='A2'");
			ResultSet rs2=ps2.executeQuery();
			while(rs2.next())
			{
				sa2=rs2.getString("status");
			}
			
			PreparedStatement ps3=con.prepareStatement("SELECT status from "+bname+" where seat='A3'");
			ResultSet rs3=ps3.executeQuery();
			while(rs3.next())
			{
				sa3=rs3.getString("status");
			}
			
			PreparedStatement ps4=con.prepareStatement("SELECT status from "+bname+" where seat='A4'");
			ResultSet rs4=ps4.executeQuery();
			while(rs4.next())
			{
				sa4=rs4.getString("status");
			}
			
			PreparedStatement ps5=con.prepareStatement("SELECT status from "+bname+" where seat='B1'");
			ResultSet rs5=ps5.executeQuery();
			while(rs5.next())
			{
				sb1=rs5.getString("status");
			}
			
			PreparedStatement ps6=con.prepareStatement("SELECT status from "+bname+" where seat='B2'");
			ResultSet rs6=ps6.executeQuery();
			while(rs6.next())
			{
				sb2=rs6.getString("status");
			}
			
			PreparedStatement ps7=con.prepareStatement("SELECT status from "+bname+" where seat='B3'");
			ResultSet rs7=ps7.executeQuery();
			while(rs7.next())
			{
				sb3=rs7.getString("status");
			}
			
			PreparedStatement ps8=con.prepareStatement("SELECT status from "+bname+" where seat='B4'");
			ResultSet rs8=ps8.executeQuery();
			while(rs8.next())
			{
				sb4=rs8.getString("status");
			}
			
			PreparedStatement ps9=con.prepareStatement("SELECT status from "+bname+" where seat='C1'");
			ResultSet rs9=ps9.executeQuery();
			while(rs9.next())
			{
				sc1=rs9.getString("status");
			}
			
			PreparedStatement ps10=con.prepareStatement("SELECT status from "+bname+" where seat='C2'");
			ResultSet rs10=ps10.executeQuery();
			while(rs10.next())
			{
				sc2=rs10.getString("status");
			}
			
			PreparedStatement ps11=con.prepareStatement("SELECT status from "+bname+" where seat='C3'");
			ResultSet rs11=ps11.executeQuery();
			while(rs11.next())
			{
				sc3=rs11.getString("status");
			}
			
			PreparedStatement ps12=con.prepareStatement("SELECT status from "+bname+" where seat='C4'");
			ResultSet rs12=ps12.executeQuery();
			while(rs12.next())
			{
				sc4=rs12.getString("status");
			}
			
			PreparedStatement ps13=con.prepareStatement("SELECT status from "+bname+" where seat='D1'");
			ResultSet rs13=ps13.executeQuery();
			while(rs13.next())
			{
				sd1=rs13.getString("status");
			}
			
			PreparedStatement ps14=con.prepareStatement("SELECT status from "+bname+" where seat='D2'");
			ResultSet rs14=ps14.executeQuery();
			while(rs14.next())
			{
				sd2=rs14.getString("status");
			}
			
			PreparedStatement ps15=con.prepareStatement("SELECT status from "+bname+" where seat='D3'");
			ResultSet rs15=ps15.executeQuery();
			while(rs15.next())
			{
				sd3=rs15.getString("status");
			}
			
			PreparedStatement ps16=con.prepareStatement("SELECT status from "+bname+" where seat='D4'");
			ResultSet rs16=ps16.executeQuery();
			while(rs16.next())
			{
				sd4=rs16.getString("status");
			}
			
			PreparedStatement ps17=con.prepareStatement("SELECT status from "+bname+" where seat='E1'");
			ResultSet rs17=ps17.executeQuery();
			while(rs17.next())
			{
				se1=rs17.getString("status");
			}
			
			PreparedStatement ps18=con.prepareStatement("SELECT status from "+bname+" where seat='E2'");
			ResultSet rs18=ps18.executeQuery();
			while(rs18.next())
			{
				se2=rs18.getString("status");
			}
			
			PreparedStatement ps19=con.prepareStatement("SELECT status from "+bname+" where seat='E3'");
			ResultSet rs19=ps19.executeQuery();
			while(rs19.next())
			{
				se3=rs19.getString("status");
			}
			
			PreparedStatement ps20=con.prepareStatement("SELECT status from "+bname+" where seat='E4'");
			ResultSet rs20=ps20.executeQuery();
			while(rs20.next())
			{
				se4=rs20.getString("status");
			}
		}
		else
		{
      out.write("\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\talert(\"No Bus Available On Selected Date\");\r\n");
      out.write("\t\t\t\t\tdocument.location.href=\"bus.jsp\";\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t");
 }
		
	}
	catch(Exception e)
	{
		
	}	
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<div class=\"plane\">\r\n");
      out.write("\t<i class=\"fas fa-paper-plane\" style=\"color:white; font-size:50px;\"></i>\r\n");
      out.write("\t&nbsp&nbsp&nbsp\r\n");
      out.write("\t<span style=\"font-size:35px;color:white;\">SwiftPay</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"title\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"home\" onclick=\"document.location.href='main.jsp'\">\r\n");
      out.write("\t<i class=\"fas fa-home\" style=\"color:white; font-size:40px;\"></i>\r\n");
      out.write("\t<span style=\"font-size:30px;color:white;\">Home</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"parent\">\r\n");
      out.write("\t<div class=\"child\">\r\n");
      out.write("\t\t<h1 style=\"margin-bottom:15px;font-size:30px;color:#666666;\">Select Seat</h1>\r\n");
      out.write("\t\t<div class=\"seat\">\r\n");
      out.write("\t\t<table height=\"450\" width=\"500\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><center>");
if(se1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E1\" value=\"E1\" id=\"E1\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E1\" value=\"E1\" id=\"E1\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>E1</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(se2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E2\" value=\"E2\" id=\"E2\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E2\" value=\"E2\" id=\"E2\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>E2</span></center></td>\r\n");
      out.write("\t\t\t\t<td>&nbsp&nbsp</td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(se3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E3\" value=\"E3\" id=\"E3\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E3\" value=\"E3\" id=\"E3\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>E3</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(se4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E4\" value=\"E4\" id=\"E4\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E4\" value=\"E4\" id=\"E4\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>E4</span></center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sd1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D1\" value=\"D1\" id=\"D1\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D1\" value=\"D1\" id=\"D1\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>D1</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sd2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D2\" value=\"D2\" id=\"D2\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D2\" value=\"D2\" id=\"D2\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>D2</span></center></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sd3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D3\" value=\"D3\" id=\"D3\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D3\" value=\"D3\" id=\"D3\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>D3</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sd4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D4\" value=\"D4\" id=\"D4\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D4\" value=\"D4\" id=\"D4\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>D4</span></center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sc1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C1\" value=\"C1\" id=\"C1\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C1\" value=\"C1\" id=\"C1\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>C1</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sc2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C2\" value=\"C2\" id=\"C2\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C2\" value=\"C2\" id=\"C2\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>C2</span></center></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sc3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C3\" value=\"C3\" id=\"C3\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C3\" value=\"C3\" id=\"C3\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>C3</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sc4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C4\" value=\"C4\" id=\"C4\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C4\" value=\"C4\" id=\"C4\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>C4</span></center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sb1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B1\" value=\"B1\" id=\"B1\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B1\" value=\"B1\" id=\"B1\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>B1</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sb2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B2\" value=\"B2\" id=\"B2\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B2\" value=\"B2\" id=\"B2\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>B2</span></center></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sb3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B3\" value=\"B3\" id=\"B3\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B3\" value=\"B3\" id=\"B3\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>B3</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sb4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B4\" value=\"B4\" id=\"B4\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B4\" value=\"B4\" id=\"B4\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>B4</span></center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sa1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A1\" value=\"A1\" id=\"A1\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A1\" value=\"A1\" id=\"A1\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>A1</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sa2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A2\" value=\"A2\" id=\"A2\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A2\" value=\"A2\" id=\"A2\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>A2</span></center></td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sa3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A3\" value=\"A3\" id=\"A3\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A3\" value=\"A3\" id=\"A3\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>A3</span></center></td>\r\n");
      out.write("\t\t\t\t<td><center>");
if(sa4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A4\" value=\"A4\" id=\"A4\" onclick=\"display(this.id)\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A4\" value=\"A4\" id=\"A4\" style=\"cursor:no-drop\" disabled>");
} 
      out.write("<br><span>A4</span></center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table width=\"500\" height=\"100\">\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label><img src=\"images java/steering.png\" height=\"50\" width=\"50\"  style=\"margin-left:80px;\"></label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table height=\"450\" width=\"500\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><center><div><label style=\"font-size:20px;margin-left:30px;\">Rs.</label><input type=\"text\" name=\"amount\" value=\"0\" id=\"ammt\" style=\"font-size:20px;border:none;\"></div></center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><center>\r\n");
      out.write("\t\t\t\t\t<h3>Payment Method:</h3><br>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"r1\" name=\"rad\" value=\"debit\">&nbsp&nbsp<font style=\"font-size:20px;\">Debit Card</font><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" autocomplete=\"off\" name=\"dcardno\" class=\"t1\" placeholder=\"Card Number\" style=\"height:35px;font-size:20px;border:none;border-bottom:2px solid #25488e;\">&nbsp&nbsp&nbsp&nbsp<input type=\"text\" autocomplete=\"off\" name=\"dcvv\" class=\"t1\" placeholder=\"CVV Number\" style=\"height:35px;font-size:20px;border:none;border-bottom:2px solid #25488e;\">\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"r2\" name=\"rad\" value=\"credit\">&nbsp&nbsp<font style=\"font-size:20px;\">Credit Card</font><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" autocomplete=\"off\" name=\"ccardno\" class=\"t2\" placeholder=\"Card Number\" style=\"height:35px;font-size:20px;border:none;border-bottom:2px solid #25488e;\">&nbsp&nbsp&nbsp&nbsp<input type=\"text\" autocomplete=\"off\" name=\"ccvv\" class=\"t2\" placeholder=\"CVV Number\" style=\"height:35px;font-size:20px;border:none;border-bottom:2px solid #25488e;\">\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" id=\"r3\" name=\"rad\" value=\"wallet\">&nbsp&nbsp<font style=\"font-size:20px;\">Wallet</font><br>\r\n");
      out.write("\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><center><input type=\"text\" name=\"upi\" placeholder=\"4-Digit Unique Code\" style=\"height:35px;width:300px;font-size:20px;border:none;border-bottom:2px solid #25488e;\"></center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><center><input type=\"submit\" value=\"Proceed\" class=\"b1\"></center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
