/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-18 15:32:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;

public final class endgame2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Endgame</title>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("margin:0px;\r\n");
      out.write("font-family:candara;\r\n");
      out.write("}\r\n");
      out.write(".header{\r\n");
      out.write("height:150px;\r\n");
      out.write("width:100%;\r\n");
      out.write("background-color:#25488e;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:space-around;\r\n");
      out.write("align-items:center;\r\n");
      out.write("}\r\n");
      out.write(".parent{\r\n");
      out.write("height:1500px;\r\n");
      out.write("width:100%;\r\n");
      out.write("background-color:#c2d1ef;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:space-around;\r\n");
      out.write("align-items:center;\r\n");
      out.write("flex-direction:column;\r\n");
      out.write("}\r\n");
      out.write(".plane{\r\n");
      out.write("height:100px;\r\n");
      out.write("width:250px;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("align-items:center;\r\n");
      out.write("}\r\n");
      out.write(".title{\r\n");
      out.write("height:120px;\r\n");
      out.write("width:700px;\r\n");
      out.write("}\r\n");
      out.write(".home{\r\n");
      out.write("height:120px;\r\n");
      out.write("width:120px;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("align-items:center;\r\n");
      out.write("flex-direction:column;\r\n");
      out.write("}\r\n");
      out.write(".home:hover{\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(".abstract{\r\n");
      out.write("height:300px;\r\n");
      out.write("width:100%;\r\n");
      out.write("position:relative;\r\n");
      out.write("}\r\n");
      out.write(".poster{\r\n");
      out.write("height:350px;\r\n");
      out.write("width:300px;\r\n");
      out.write("background-color:white;\r\n");
      out.write("display:flex;\r\n");
      out.write("position:absolute;\r\n");
      out.write("bottom:-180px;\r\n");
      out.write("left:80px;\r\n");
      out.write("}\r\n");
      out.write(".img{\r\n");
      out.write("display:block;\r\n");
      out.write("height:300px;\r\n");
      out.write("width:100%;\r\n");
      out.write("}\r\n");
      out.write(".synopsis{\r\n");
      out.write("height:150px;\r\n");
      out.write("width:700px;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("align-items:center;\r\n");
      out.write("}\r\n");
      out.write(".child{\r\n");
      out.write("height:600px;\r\n");
      out.write("width:80%;\r\n");
      out.write("background-color:white;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:space-around;\r\n");
      out.write("align-items:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".b1{\r\n");
      out.write("height:35px;\r\n");
      out.write("width:300px;\r\n");
      out.write("font-size:20px;\r\n");
      out.write("border-radius:4px;\r\n");
      out.write("}\r\n");
      out.write(".b1:hover{\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("background-color:#25488e;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write(".t1{\r\n");
      out.write("display:none;\r\n");
      out.write("}\r\n");
      out.write(".t2{\r\n");
      out.write("display:none;\r\n");
      out.write("}\r\n");
      out.write(".seatname{\r\n");
      out.write("height:580px;\r\n");
      out.write("width:220px;\r\n");
      out.write("display:flex;\r\n");
      out.write("align-items:center;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("}\r\n");
      out.write(".seat{\r\n");
      out.write("height:550px;\r\n");
      out.write("width:900px;\r\n");
      out.write("display:flex;\r\n");
      out.write("align-items:center;\r\n");
      out.write("justify-content:space-around;\r\n");
      out.write("flex-direction:column;\r\n");
      out.write("}\r\n");
      out.write(".test{\r\n");
      out.write("height:30px;\r\n");
      out.write("width:30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src='javascript/jquery-3.4.1.js'>\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#r1\").click(function(){\r\n");
      out.write("\t$(\".t2\").hide();\r\n");
      out.write("\t$(\".t1\").toggle(\"slow\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#r2\").click(function(){\r\n");
      out.write("\t$(\".t1\").hide();\r\n");
      out.write("\t$(\".t2\").toggle(\"slow\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#r3\").click(function(){\r\n");
      out.write("\t$(\".t1\").hide();\r\n");
      out.write("\t$(\".t2\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("function display(id)\r\n");
      out.write("{\r\n");
      out.write("\tvar amount = document.getElementById(\"ammt\").value;\r\n");
      out.write("\tvar result = new XMLHttpRequest();\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.getElementById(id).checked == true)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tresult.onreadystatechange = function(){\r\n");
      out.write("\t\t\tif(this.readyState == 4 && this.status == 200)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar x = document.getElementById('ammt');\r\n");
      out.write("\t\t\t\tx.value = this.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tresult.open(\"GET\",\"MovieSelect.jsp?id=\"+id+\"&amount=\"+amount,true);\r\n");
      out.write("\t\tresult.send();\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tresult.onreadystatechange = function(){\r\n");
      out.write("\t\t\tif(this.readyState == 4 && this.status == 200)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar x = document.getElementById('ammt');\r\n");
      out.write("\t\t\t\tx.value = this.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tresult.open(\"GET\",\"MovieUnselect.jsp?id=\"+id+\"&amount=\"+amount,true);\r\n");
      out.write("\t\tresult.send();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"css/all.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"Endgame\" method=\"POST\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String theater=request.getParameter("theater");
String time=request.getParameter("time");
String mdate=request.getParameter("mdate");

Cookie cookie10=new Cookie("etheater",theater+"");
Cookie cookie11=new Cookie("etime",time+"");
Cookie cookie12=new Cookie("emdate",mdate+"");
response.addCookie(cookie10);
response.addCookie(cookie11);
response.addCookie(cookie12);

String sa1="",sa2="",sa3="",sa4="",sa5="",sa6="";
String sb1="",sb2="",sb3="",sb4="",sb5="",sb6="";
String sc1="",sc2="",sc3="",sc4="",sc5="",sc6="";
String sd1="",sd2="",sd3="",sd4="",sd5="",sd6="";
String se1="",se2="",se3="",se4="",se5="",se6="";
String sf1="",sf2="",sf3="",sf4="",sf5="",sf6="";

Connection con=null;
String url="jdbc:ucanaccess://E://Database//movie.accdb";
String th="",ti="",da="",tname="";
try{
	Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
	con=DriverManager.getConnection(url);
	Statement stmt = con.createStatement();
	ResultSet rs=stmt.executeQuery("select * from endgame where theater='"+theater+"' and time='"+time+"' and mdate='"+mdate+"'");
	while(rs.next())
	{
		th=rs.getString("theater");
		ti=rs.getString("time");
		da=rs.getString("mdate");
		tname=rs.getString("tname");
	}
	if(theater.equals(th) && time.equals(ti) && mdate.equals(da))
	{
		PreparedStatement ps1=con.prepareStatement("select * from "+tname+" where seat='A1'");
		ResultSet rs1=ps1.executeQuery();
		while(rs1.next())
		{
			sa1=rs1.getString("status");
		}
		PreparedStatement ps2=con.prepareStatement("select * from "+tname+" where seat='A2'");
		ResultSet rs2=ps2.executeQuery();
		while(rs2.next())
		{
			sa2=rs2.getString("status");
		}
		PreparedStatement ps3=con.prepareStatement("select * from "+tname+" where seat='A3'");
		ResultSet rs3=ps3.executeQuery();
		while(rs3.next())
		{
			sa3=rs3.getString("status");
		}
		PreparedStatement ps4=con.prepareStatement("select * from "+tname+" where seat='A4'");
		ResultSet rs4=ps4.executeQuery();
		while(rs4.next())
		{
			sa4=rs4.getString("status");
		}
		PreparedStatement ps5=con.prepareStatement("select * from "+tname+" where seat='A5'");
		ResultSet rs5=ps5.executeQuery();
		while(rs5.next())
		{
			sa5=rs5.getString("status");
		}
		PreparedStatement ps6=con.prepareStatement("select * from "+tname+" where seat='A6'");
		ResultSet rs6=ps6.executeQuery();
		while(rs6.next())
		{
			sa6=rs6.getString("status");
		}
		
		
		
		PreparedStatement ps7=con.prepareStatement("select * from "+tname+" where seat='B1'");
		ResultSet rs7=ps7.executeQuery();
		while(rs7.next())
		{
			sb1=rs7.getString("status");
		}
		PreparedStatement ps8=con.prepareStatement("select * from "+tname+" where seat='B2'");
		ResultSet rs8=ps8.executeQuery();
		while(rs8.next())
		{
			sb2=rs8.getString("status");
		}
		PreparedStatement ps9=con.prepareStatement("select * from "+tname+" where seat='B3'");
		ResultSet rs9=ps9.executeQuery();
		while(rs9.next())
		{
			sb3=rs9.getString("status");
		}
		PreparedStatement ps10=con.prepareStatement("select * from "+tname+" where seat='B4'");
		ResultSet rs10=ps10.executeQuery();
		while(rs10.next())
		{
			sb4=rs10.getString("status");
		}
		PreparedStatement ps11=con.prepareStatement("select * from "+tname+" where seat='B5'");
		ResultSet rs11=ps11.executeQuery();
		while(rs11.next())
		{
			sb5=rs11.getString("status");
		}
		PreparedStatement ps12=con.prepareStatement("select * from "+tname+" where seat='B6'");
		ResultSet rs12=ps12.executeQuery();
		while(rs12.next())
		{
			sb6=rs12.getString("status");
		}
		
		
		PreparedStatement ps13=con.prepareStatement("select * from "+tname+" where seat='C1'");
		ResultSet rs13=ps13.executeQuery();
		while(rs13.next())
		{
			sc1=rs13.getString("status");
		}
		PreparedStatement ps14=con.prepareStatement("select * from "+tname+" where seat='C2'");
		ResultSet rs14=ps14.executeQuery();
		while(rs14.next())
		{
			sc2=rs14.getString("status");
		}
		PreparedStatement ps15=con.prepareStatement("select * from "+tname+" where seat='C3'");
		ResultSet rs15=ps15.executeQuery();
		while(rs15.next())
		{
			sc3=rs15.getString("status");
		}
		PreparedStatement ps16=con.prepareStatement("select * from "+tname+" where seat='C4'");
		ResultSet rs16=ps16.executeQuery();
		while(rs16.next())
		{
			sc4=rs16.getString("status");
		}
		PreparedStatement ps17=con.prepareStatement("select * from "+tname+" where seat='C5'");
		ResultSet rs17=ps17.executeQuery();
		while(rs17.next())
		{
			sc5=rs17.getString("status");
		}
		PreparedStatement ps18=con.prepareStatement("select * from "+tname+" where seat='C6'");
		ResultSet rs18=ps18.executeQuery();
		while(rs18.next())
		{
			sc6=rs18.getString("status");
		}
		
		
		PreparedStatement ps19=con.prepareStatement("select * from "+tname+" where seat='D1'");
		ResultSet rs19=ps19.executeQuery();
		while(rs19.next())
		{
			sd1=rs19.getString("status");
		}
		PreparedStatement ps20=con.prepareStatement("select * from "+tname+" where seat='D2'");
		ResultSet rs20=ps20.executeQuery();
		while(rs20.next())
		{
			sd2=rs20.getString("status");
		}
		PreparedStatement ps21=con.prepareStatement("select * from "+tname+" where seat='D3'");
		ResultSet rs21=ps21.executeQuery();
		while(rs21.next())
		{
			sd3=rs21.getString("status");
		}
		PreparedStatement ps22=con.prepareStatement("select * from "+tname+" where seat='D4'");
		ResultSet rs22=ps22.executeQuery();
		while(rs22.next())
		{
			sd4=rs22.getString("status");
		}
		PreparedStatement ps23=con.prepareStatement("select * from "+tname+" where seat='D5'");
		ResultSet rs23=ps23.executeQuery();
		while(rs23.next())
		{
			sd5=rs23.getString("status");
		}
		PreparedStatement ps24=con.prepareStatement("select * from "+tname+" where seat='D6'");
		ResultSet rs24=ps24.executeQuery();
		while(rs24.next())
		{
			sd6=rs24.getString("status");
		}
		
		
		PreparedStatement ps25=con.prepareStatement("select * from "+tname+" where seat='E1'");
		ResultSet rs25=ps25.executeQuery();
		while(rs25.next())
		{
			se1=rs25.getString("status");
		}
		PreparedStatement ps26=con.prepareStatement("select * from "+tname+" where seat='E2'");
		ResultSet rs26=ps26.executeQuery();
		while(rs26.next())
		{
			se2=rs26.getString("status");
		}
		PreparedStatement ps27=con.prepareStatement("select * from "+tname+" where seat='E3'");
		ResultSet rs27=ps27.executeQuery();
		while(rs27.next())
		{
			se3=rs27.getString("status");
		}
		PreparedStatement ps28=con.prepareStatement("select * from "+tname+" where seat='E4'");
		ResultSet rs28=ps28.executeQuery();
		while(rs28.next())
		{
			se4=rs28.getString("status");
		}
		PreparedStatement ps29=con.prepareStatement("select * from "+tname+" where seat='E5'");
		ResultSet rs29=ps29.executeQuery();
		while(rs29.next())
		{
			se5=rs29.getString("status");
		}
		PreparedStatement ps30=con.prepareStatement("select * from "+tname+" where seat='E6'");
		ResultSet rs30=ps30.executeQuery();
		while(rs30.next())
		{
			se6=rs30.getString("status");
		}
		
		
		PreparedStatement ps31=con.prepareStatement("select * from "+tname+" where seat='F1'");
		ResultSet rs31=ps31.executeQuery();
		while(rs31.next())
		{
			sf1=rs31.getString("status");
		}
		PreparedStatement ps32=con.prepareStatement("select * from "+tname+" where seat='F2'");
		ResultSet rs32=ps32.executeQuery();
		while(rs32.next())
		{
			sf2=rs32.getString("status");
		}
		PreparedStatement ps33=con.prepareStatement("select * from "+tname+" where seat='F3'");
		ResultSet rs33=ps33.executeQuery();
		while(rs33.next())
		{
			sf3=rs33.getString("status");
		}
		PreparedStatement ps34=con.prepareStatement("select * from "+tname+" where seat='F4'");
		ResultSet rs34=ps34.executeQuery();
		while(rs34.next())
		{
			sf4=rs34.getString("status");
		}
		PreparedStatement ps35=con.prepareStatement("select * from "+tname+" where seat='F5'");
		ResultSet rs35=ps35.executeQuery();
		while(rs35.next())
		{
			sf5=rs35.getString("status");
		}
		PreparedStatement ps36=con.prepareStatement("select * from "+tname+" where seat='F6'");
		ResultSet rs36=ps36.executeQuery();
		while(rs36.next())
		{
			sf6=rs36.getString("status");
		}
	}
	else
	{
		//no movie on selected date and time
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"No movie Available On Selected Date\");\r\n");
      out.write("\t\t\tdocument.location.href=\"endgame1.jsp\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");
}
}
catch(Exception e)
{
	
}

      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t<div class=\"plane\">\r\n");
      out.write("\t<i class=\"fas fa-paper-plane\" style=\"color:white; font-size:50px;\"></i>\r\n");
      out.write("\t&nbsp&nbsp&nbsp\r\n");
      out.write("\t<span style=\"font-size:35px;color:white;\">SwiftPay</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"title\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"home\" onclick=\"\">\r\n");
      out.write("\t<i class=\"fas fa-home\" style=\"color:white; font-size:40px;\"></i>\r\n");
      out.write("\t<span style=\"font-size:30px;color:white;\">Home</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"abstract\">\r\n");
      out.write("\t<img src=\"images java/abstract.jpg\" class=\"img\">\r\n");
      out.write("\t<div class=\"poster\">\r\n");
      out.write("\t\t<img src=\"images java/endgame.jpg\" height=\"350\" width=\"300\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"parent\">\r\n");
      out.write("\t<div class=\"synopsis\">\r\n");
      out.write("\t\t<h1 style=\"margin-bottom:15px;font-size:30px;color:black;\">Avengers Endgame</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"child\">\r\n");
      out.write("\t\t<div class=\"seatname\">\r\n");
      out.write("\t\t\t<table height=\"500\" width=\"200\" style=\"margin-bottom:40px;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center><span style=\"font-size:20px;\">Premium <br>Rs.300</span></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center><span style=\"font-size:20px;\">Executive <br>Rs.200</span></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center><span style=\"font-size:20px;\">Normal <br>Rs.100</span></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"seat\">\r\n");
      out.write("\t\t\t<table height=\"130\" width=\"800\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sf1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F1\" value=\"F1\" id=\"F1\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F1\" value=\"F1\" id=\"F1\" disabled>");
} 
      out.write("<br><span>F1</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sf2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F2\" value=\"F2\" id=\"F2\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F2\" value=\"F2\" id=\"F2\" disabled>");
} 
      out.write("<br><span>F2</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sf3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F3\" value=\"F3\" id=\"F3\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F3\" value=\"F3\" id=\"F3\" disabled>");
} 
      out.write("<br><span>F3</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sf4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F4\" value=\"F4\" id=\"F4\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F4\" value=\"F4\" id=\"F4\" disabled>");
} 
      out.write("<br><span>F4</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sf5.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F5\" value=\"F5\" id=\"F5\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F5\" value=\"F5\" id=\"F5\" disabled>");
} 
      out.write("<br><span>F5</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sf6.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F6\" value=\"F6\" id=\"F6\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"F6\" value=\"F6\" id=\"F6\" disabled>");
} 
      out.write("<br><span>F6</span></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(se1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E1\" value=\"E1\" id=\"E1\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E1\" value=\"E1\" id=\"E1\" disabled>");
} 
      out.write("<br><span>E1</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(se2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E2\" value=\"E2\" id=\"E2\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E2\" value=\"E2\" id=\"E2\" disabled>");
} 
      out.write("<br><span>E2</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(se3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E3\" value=\"E3\" id=\"E3\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E3\" value=\"E3\" id=\"E3\" disabled>");
} 
      out.write("<br><span>E3</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(se4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E4\" value=\"E4\" id=\"E4\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E4\" value=\"E4\" id=\"E4\" disabled>");
} 
      out.write("<br><span>E4</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(se5.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E5\" value=\"E5\" id=\"E5\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E5\" value=\"E5\" id=\"E5\" disabled>");
} 
      out.write("<br><span>E5</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(se6.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E6\" value=\"E6\" id=\"E6\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"E6\" value=\"E6\" id=\"E6\" disabled>");
} 
      out.write("<br><span>E6</span></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table height=\"130\" width=\"800\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sd1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D1\" value=\"D1\" id=\"D1\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D1\" value=\"D1\" id=\"D1\" disabled>");
} 
      out.write("<br><span>D1</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sd2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D2\" value=\"D2\" id=\"D2\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D2\" value=\"D2\" id=\"D2\" disabled>");
} 
      out.write("<br><span>D2</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sd3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D3\" value=\"D3\" id=\"D3\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D3\" value=\"D3\" id=\"D3\" disabled>");
} 
      out.write("<br><span>D3</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sd4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D4\" value=\"D4\" id=\"D4\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D4\" value=\"D4\" id=\"D4\" disabled>");
} 
      out.write("<br><span>D4</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sd5.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D5\" value=\"D5\" id=\"D5\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D5\" value=\"D5\" id=\"D5\" disabled>");
} 
      out.write("<br><span>D5</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sd6.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D6\" value=\"D6\" id=\"D6\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"D6\" value=\"D6\" id=\"D6\" disabled>");
} 
      out.write("<br><span>D6</span></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sc1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C1\" value=\"C1\" id=\"C1\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C1\" value=\"C1\" id=\"C1\" disabled>");
} 
      out.write("<br><span>C1</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sc2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C2\" value=\"C2\" id=\"C2\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C2\" value=\"C2\" id=\"C2\" disabled>");
} 
      out.write("<br><span>C2</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sc3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C3\" value=\"C3\" id=\"C3\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C3\" value=\"C3\" id=\"C3\" disabled>");
} 
      out.write("<br><span>C3</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sc4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C4\" value=\"C4\" id=\"C4\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C4\" value=\"C4\" id=\"C4\" disabled>");
} 
      out.write("<br><span>C4</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sc5.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C5\" value=\"C5\" id=\"C5\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C5\" value=\"C5\" id=\"C5\" disabled>");
} 
      out.write("<br><span>C5</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sc6.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C6\" value=\"C6\" id=\"C6\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"C6\" value=\"C6\" id=\"C6\" disabled>");
} 
      out.write("<br><span>C6</span></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table height=\"130\" width=\"800\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sb1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B1\" value=\"B1\" id=\"B1\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B1\" value=\"B1\" id=\"B1\" disabled>");
} 
      out.write("<br><span>B1</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sb2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B2\" value=\"B2\" id=\"B2\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B2\" value=\"B2\" id=\"B2\" disabled>");
} 
      out.write("<br><span>B2</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sb3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B3\" value=\"B3\" id=\"B3\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B3\" value=\"B3\" id=\"B3\" disabled>");
} 
      out.write("<br><span>B3</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sb4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B4\" value=\"B4\" id=\"B4\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B4\" value=\"B4\" id=\"B4\" disabled>");
} 
      out.write("<br><span>B4</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sb5.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B5\" value=\"B5\" id=\"B5\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B5\" value=\"B5\" id=\"B5\" disabled>");
} 
      out.write("<br><span>B5</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sb6.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B6\" value=\"B6\" id=\"B6\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"B6\" value=\"B6\" id=\"B6\" disabled>");
} 
      out.write("<br><span>B6</span></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sa1.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A1\" value=\"A1\" id=\"A1\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A1\" value=\"A1\" id=\"A1\" disabled>");
} 
      out.write("<br><span>A1</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sa2.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A2\" value=\"A2\" id=\"A2\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A2\" value=\"A2\" id=\"A2\" disabled>");
} 
      out.write("<br><span>A2</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sa3.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A3\" value=\"A3\" id=\"A3\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A3\" value=\"A3\" id=\"A3\" disabled>");
} 
      out.write("<br><span>A3</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sa4.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A4\" value=\"A4\" id=\"A4\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A4\" value=\"A4\" id=\"A4\" disabled>");
} 
      out.write("<br><span>A4</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sa5.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A5\" value=\"A5\" id=\"A5\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A5\" value=\"A5\" id=\"A5\" disabled>");
} 
      out.write("<br><span>A5</span></center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
if(sa6.equals("notbooked")){ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A6\" value=\"A6\" id=\"A6\" onclick=\"display(this.id);\">");
}else{ 
      out.write("<input type=\"checkbox\" class=\"test\" name=\"A6\" value=\"A6\" id=\"A6\" disabled>");
} 
      out.write("<br><span>A6</span></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center><div><label style=\"font-size:20px;margin-left:30px;\">Rs.</label><input type=\"text\" name=\"amount\" value=\"0\" id=\"ammt\" style=\"font-size:20px;border:none;\"></div></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"child\">\r\n");
      out.write("\t\t\t<table height=\"450\" width=\"550\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center>\r\n");
      out.write("\t\t\t\t\t\t<h3>Payment Method:</h3><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"r1\" name=\"rad\" value=\"debit\">&nbsp&nbsp<font style=\"font-size:20px;\">Debit Card</font><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" autocomplete=\"off\" name=\"dcardno\" class=\"t1\" placeholder=\"Card Number\" style=\"height:35px;font-size:20px;border:none;border-bottom:2px solid #25488e;\">&nbsp&nbsp&nbsp&nbsp<input type=\"text\" autocomplete=\"off\" name=\"dcvv\" class=\"t1\" placeholder=\"CVV Number\" style=\"height:35px;font-size:20px;border:none;border-bottom:2px solid #25488e;\">\r\n");
      out.write("\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"r2\" name=\"rad\" value=\"credit\">&nbsp&nbsp<font style=\"font-size:20px;\">Credit Card</font><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" autocomplete=\"off\" name=\"ccardno\" class=\"t2\" placeholder=\"Card Number\" style=\"height:35px;font-size:20px;border:none;border-bottom:2px solid #25488e;\">&nbsp&nbsp&nbsp&nbsp<input type=\"text\" autocomplete=\"off\" name=\"ccvv\" class=\"t2\" placeholder=\"CVV Number\" style=\"height:35px;font-size:20px;border:none;border-bottom:2px solid #25488e;\">\r\n");
      out.write("\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"r3\" name=\"rad\" value=\"wallet\">&nbsp&nbsp<font style=\"font-size:20px;\">Wallet</font><br>\r\n");
      out.write("\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center><input type=\"text\" autocomplete=\"off\" name=\"upi\" placeholder=\"4-Digit Code\" style=\"height:35px;width:300px;font-size:20px;border:none;border-bottom:2px solid #25488e;\"></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center><input type=\"submit\" value=\"Book Ticket\" class=\"b1\"></center></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
